[tools]
bat = "latest"
bitwarden = "latest"
choose = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
hyperfine = "latest"
julia = "latest"
neovim = "stable"
node = "latest"
poetry = "latest"
python = "3.11.7"
ripgrep = "latest"
ruby = "latest"
rust = "latest"
tokei = "latest"
zoxide = "latest"
