# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

apply = ["defer"]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
proto = "ssh"
apply = ["source"]

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins]
# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"

[plugins.compinit]
inline = "autoload -Uz compinit && zsh-defer compinit"

[plugins.prezto-editor]
remote = "https://raw.githubusercontent.com/sorin-ionescu/prezto/master/modules/editor/init.zsh"
apply = ["source"]

[plugins.prezto-spectrum]
remote = "https://raw.githubusercontent.com/sorin-ionescu/prezto/master/modules/spectrum/init.zsh"

[plugins.ohmyzsh-plugin]
github = "ohmyzsh/ohmyzsh"
proto = "ssh"
dir = "plugins"
use = ["{command-not-found,gpg-agent}/*.plugin.zsh"]

[plugins.dot-expansion]
github = "wazum/zsh-directory-dot-expansion"
proto = "ssh"

[plugins.cmd-time]
github = "popstas/zsh-command-time"
proto = "ssh"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
proto = "ssh"
dir = "src"
apply = ["fpath"]

[plugins.faster-syntax-highlighting]
github = "z-shell/F-Sy-H"
proto = "ssh"
use = ["F-Sy-H.plugin.zsh"]

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
proto = "ssh"
use = ["{{ name }}.zsh"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
proto = "ssh"
use = ["{{ name }}.zsh"]

[plugins.git-prompt]
github = "woefe/git-prompt.zsh"
proto = "ssh"
use = ["{{ name }}.zsh"]

[plugins.syncload]
local = "~/.config/zsh"
use = ["{keybind,path,sh-conf}.zsh"]
apply = ["source"]

[plugins.lazyload]
local = "~/.config/zsh"
use = ["{alias,plugin-conf,prompt}.zsh"]

[plugins.mise]
inline = 'zsh-defer eval "$(mise activate zsh)"'
